# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sUmB0ySOadH2uylhswU6vGSFFtu7sw_N
"""

import pytest

def mult(num1, num2):
  return num1 * num2

def verificaPositivo(num):
  if num < 0:
    return 'Número negativo'
  else:
    return 'Número positivo'

def test_mult(): 
  assert mult(5, 4) == 20 


def test_verificaPositivo():
  assert verificaPositivo(10) == 'Número positivo'


def test_verificaPositivo():
  assert verificaPositivo(-2) == 'Número negativo'